"""
Django settings for nhs_genie_project project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dotenv
from pathlib import Path
from typing import List, Optional

from django.core.exceptions import ImproperlyConfigured

# Environment file variables parsing helpers.
def env_bool(name: str, default: bool = False) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return str(val).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: Optional[List[str]] = None) -> List[str]:
    val = os.getenv(name)
    if not val:
        return default or []
    return [item.strip() for item in val.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables.
dotenv_path = BASE_DIR / ".env"
if dotenv_path.is_file():
    dotenv.load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

USE_WHITENOISE = env_bool("USE_WHITENOISE", default=False)

DB_NAME = os.getenv("DB_NAME") or 'db.sqlite3'

# Enforce SECRET_KEY presence in non-debug environments
if not SECRET_KEY:
    # Provide dev fallback.
    if DEBUG:
        SECRET_KEY = "dev-insecure-secret-key"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set when DEBUG is False.")

GENIE_VERSION = os.getenv("GENIE_VERSION") or ''

DATA_FOLDER = os.getenv("DATA_FOLDER") or BASE_DIR / 'data'

GENIE_VCF = os.getenv("GENIE_VCF") or None
if GENIE_VCF:
    GENIE_VCF = DATA_FOLDER / GENIE_VCF
GENIE_CANCER_TYPES_CSV = os.getenv("GENIE_CANCER_TYPES_CSV") or None
if GENIE_CANCER_TYPES_CSV:
    GENIE_CANCER_TYPES_CSV = DATA_FOLDER / GENIE_CANCER_TYPES_CSV

ALLOWED_HOSTS = [*env_list("ALLOWED_HOSTS"), "127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
if not CSRF_TRUSTED_ORIGINS:
    if DEBUG:
        CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1", "http://localhost"]
    else:
        CSRF_TRUSTED_ORIGINS = [
            f"https://{h}" for h in ALLOWED_HOSTS
            if h not in {"127.0.0.1", "localhost"}
        ]

# Honour X-Forwarded-Proto from the proxy (safe even when running over HTTP)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fontawesomefree",
    "main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    *(["whitenoise.middleware.WhiteNoiseMiddleware"] if USE_WHITENOISE else []),
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nhs_genie_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.genie_version",
            ],
        },
    },
]

WSGI_APPLICATION = "nhs_genie_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "data" / DB_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_DIR = BASE_DIR / "static"
STATIC_URL = "/static/"
STATICFILES_DIRS = [STATIC_DIR]
STATIC_ROOT = BASE_DIR / "staticfiles"

if USE_WHITENOISE:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"