# Generated by Django 4.2.23 on 2025-08-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CancerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancer_type", models.CharField(max_length=255)),
                ("cancer_type_vcf", models.CharField(max_length=255)),
                ("is_haemonc", models.BooleanField()),
                ("total_patient_count", models.PositiveIntegerField()),
            ],
            options={"db_table": "main_cancer_type",},
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chrom", models.CharField(max_length=100)),
                ("pos", models.IntegerField()),
                ("ref", models.TextField()),
                ("alt", models.TextField()),
                (
                    "gene_symbol",
                    models.CharField(help_text="Hugo_Symbol", max_length=100),
                ),
                (
                    "refseq_transcript",
                    models.CharField(help_text="RefSeq", max_length=100, null=True),
                ),
                (
                    "consequence",
                    models.CharField(help_text="Consequence", max_length=600),
                ),
                (
                    "classification",
                    models.CharField(
                        help_text="Variant_Classification", max_length=600
                    ),
                ),
                ("hgvs_c", models.TextField(help_text="HGVSc", null=True)),
                ("hgvs_p", models.TextField(help_text="HGVSp", null=True)),
                (
                    "original_description",
                    models.TextField(help_text="Genie_description"),
                ),
                (
                    "original_contig",
                    models.CharField(
                        help_text="OriginalContig", max_length=100, null=True
                    ),
                ),
                (
                    "original_start",
                    models.IntegerField(help_text="OriginalStart", null=True),
                ),
                (
                    "all_cancers_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="SameNucleotideChange_All_Cancers_Count_N_160761",
                    ),
                ),
                (
                    "haemonc_cancers_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="SameNucleotideChange_Haemonc_Cancers_Count_N_13906",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantCancerTypePatientCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("same_nucleotide_change_pc", models.PositiveIntegerField()),
                ("same_amino_acid_change_pc", models.PositiveIntegerField()),
                (
                    "same_or_downstream_truncating_variants_per_cds_pc",
                    models.PositiveIntegerField(),
                ),
                ("nested_inframe_deletions_per_cds_pc", models.PositiveIntegerField()),
                (
                    "cancer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cancertype",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.variant"
                    ),
                ),
            ],
            options={"db_table": "main_variant_cancer_type_patient_count",},
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["gene_symbol"], name="main_varian_gene_sy_d69036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["chrom", "pos"], name="main_varian_chrom_a1e9f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                fields=("chrom", "pos", "ref", "alt"), name="uniq_variant_locus_allele"
            ),
        ),
    ]
