# Generated by Django 4.2.23 on 2025-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chrom", models.CharField(max_length=100)),
                ("pos", models.IntegerField()),
                ("ref", models.TextField()),
                ("alt", models.TextField()),
                (
                    "gene_symbol",
                    models.CharField(help_text="Hugo_Symbol", max_length=100),
                ),
                (
                    "refseq_transcript",
                    models.CharField(help_text="RefSeq", max_length=100, null=True),
                ),
                (
                    "consequence",
                    models.CharField(help_text="Consequence", max_length=600),
                ),
                (
                    "classification",
                    models.CharField(
                        help_text="Variant_Classification", max_length=600
                    ),
                ),
                ("hgvs_c", models.TextField(help_text="HGVSc", null=True)),
                ("hgvs_p", models.TextField(help_text="HGVSp", null=True)),
                (
                    "original_description",
                    models.TextField(help_text="Genie_description"),
                ),
                (
                    "original_contig",
                    models.CharField(
                        help_text="OriginalContig", max_length=100, null=True
                    ),
                ),
                (
                    "original_start",
                    models.IntegerField(help_text="OriginalStart", null=True),
                ),
                (
                    "angiomatoid_fibrous_histiocytoma_count",
                    models.IntegerField(
                        default=0,
                        help_text="Angiomatoid_Fibrous_Histiocytoma_count",
                        verbose_name="PC_HaemOnc:Angiomatoid Fibrous Histiocytoma",
                    ),
                ),
                (
                    "b_lymphoblastic_leukemia_lymphoma_count",
                    models.IntegerField(
                        default=0,
                        help_text="B_Lymphoblastic_Leukemia_Lymphoma_count",
                        verbose_name="PC_HaemOnc:B Lymphoblastic Leukemia Lymphoma",
                    ),
                ),
                (
                    "blastic_plasmacytoid_dendritic_cell_neoplasm_count",
                    models.IntegerField(
                        default=0,
                        help_text="Blastic_Plasmacytoid_Dendritic_Cell_Neoplasm_count",
                        verbose_name="PC_HaemOnc:Blastic Plasmacytoid Dendritic Cell Neoplasm",
                    ),
                ),
                (
                    "blood_cancer_nos_count",
                    models.IntegerField(
                        default=0,
                        help_text="Blood_Cancer_NOS_count",
                        verbose_name="PC_HaemOnc:Blood Cancer NOS",
                    ),
                ),
                (
                    "blood_cancer_count",
                    models.IntegerField(
                        default=0,
                        help_text="Blood_Cancer_count",
                        verbose_name="PC_HaemOnc:Blood Cancer",
                    ),
                ),
                (
                    "histiocytosis_count",
                    models.IntegerField(
                        default=0,
                        help_text="Histiocytosis_count",
                        verbose_name="PC_HaemOnc:Histiocytosis",
                    ),
                ),
                (
                    "hodgkin_lymphoma_count",
                    models.IntegerField(
                        default=0,
                        help_text="Hodgkin_Lymphoma_count",
                        verbose_name="PC_HaemOnc:Hodgkin Lymphoma",
                    ),
                ),
                (
                    "leukemia_count",
                    models.IntegerField(
                        default=0,
                        help_text="Leukemia_count",
                        verbose_name="PC_HaemOnc:Leukemia",
                    ),
                ),
                (
                    "lymphatic_cancer_nos_count",
                    models.IntegerField(
                        default=0,
                        help_text="Lymphatic_Cancer_NOS_count",
                        verbose_name="PC_HaemOnc:Lymphatic Cancer NOS",
                    ),
                ),
                (
                    "lymphatic_cancer_count",
                    models.IntegerField(
                        default=0,
                        help_text="Lymphatic_Cancer_count",
                        verbose_name="PC_HaemOnc:Lymphatic Cancer",
                    ),
                ),
                (
                    "mastocytosis_count",
                    models.IntegerField(
                        default=0,
                        help_text="Mastocytosis_count",
                        verbose_name="PC_HaemOnc:Mastocytosis",
                    ),
                ),
                (
                    "mature_b_cell_neoplasms_count",
                    models.IntegerField(
                        default=0,
                        help_text="Mature_B_Cell_Neoplasms_count",
                        verbose_name="PC_HaemOnc:Mature B Cell Neoplasms",
                    ),
                ),
                (
                    "mature_t_and_nk_neoplasms_count",
                    models.IntegerField(
                        default=0,
                        help_text="Mature_T_and_NK_Neoplasms_count",
                        verbose_name="PC_HaemOnc:Mature T and NK Neoplasms",
                    ),
                ),
                (
                    "myelodysplastic_myeloproliferative_neoplasms_count",
                    models.IntegerField(
                        default=0,
                        help_text="Myelodysplastic_Myeloproliferative_Neoplasms_count",
                        verbose_name="PC_HaemOnc:Myelodysplastic Myeloproliferative Neoplasms",
                    ),
                ),
                (
                    "myelodysplastic_syndromes_count",
                    models.IntegerField(
                        default=0,
                        help_text="Myelodysplastic_Syndromes_count",
                        verbose_name="PC_HaemOnc:Myelodysplastic Syndromes",
                    ),
                ),
                (
                    "myeloid_neoplasms_with_germ_line_predisposition_count",
                    models.IntegerField(
                        default=0,
                        help_text="Myeloid_Neoplasms_with_Germ_Line_Predisposition_count",
                        verbose_name="PC_HaemOnc:Myeloid Neoplasms with Germ Line Predisposition",
                    ),
                ),
                (
                    "myeloproliferative_neoplasms_count",
                    models.IntegerField(
                        default=0,
                        help_text="Myeloproliferative_Neoplasms_count",
                        verbose_name="PC_HaemOnc:Myeloproliferative Neoplasms",
                    ),
                ),
                (
                    "non_hodgkin_lymphoma_count",
                    models.IntegerField(
                        default=0,
                        help_text="Non_Hodgkin_Lymphoma_count",
                        verbose_name="PC_HaemOnc:Non Hodgkin Lymphoma",
                    ),
                ),
                (
                    "posttransplant_lymphoproliferative_disorders_count",
                    models.IntegerField(
                        default=0,
                        help_text="Posttransplant_Lymphoproliferative_Disorders_count",
                        verbose_name="PC_HaemOnc:Posttransplant Lymphoproliferative Disorders",
                    ),
                ),
                (
                    "t_lymphoblastic_leukemia_lymphoma_count",
                    models.IntegerField(
                        default=0,
                        help_text="T_Lymphoblastic_Leukemia_Lymphoma_count",
                        verbose_name="PC_HaemOnc:T Lymphoblastic Leukemia Lymphoma",
                    ),
                ),
                (
                    "all_cancers_count",
                    models.IntegerField(default=0, help_text="all_cancers_count"),
                ),
                (
                    "haemonc_cancers_count",
                    models.IntegerField(default=0, help_text="haemonc_cancers_count"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["gene_symbol"], name="main_varian_gene_sy_d69036_idx"
                    ),
                    models.Index(
                        fields=["chrom", "pos"], name="main_varian_chrom_a1e9f7_idx"
                    ),
                ],
            },
        ),
    ]
