# Generated by Django 4.2.23 on 2025-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancertype",
            name="is_solid",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variant",
            name="solid_cancers_count",
            field=models.PositiveIntegerField(
                default=0, help_text="SameNucleotideChange_Solid_Cancers"
            ),
        ),
    ]
