# Generated by Django 5.2.5 on 2025-09-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_cancertype_is_solid_variant_solid_cancers_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variantcancertypepatientcount",
            old_name="nested_inframe_deletions_per_cds_pc",
            new_name="nested_inframe_deletions_per_aa_pc",
        ),
    ]
