# Generated by Django 5.2.5 on 2026-05-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nested_inframe_deletions_per_cds_pc_variantcancertypepatientcount_nested_inframe_deletions_pe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantcancertypepatientcount',
            old_name='same_or_downstream_truncating_variants_per_cds_pc',
            new_name='same_or_downstream_truncating_variants_per_aa_pc',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='classification',
        ),
    ]
