# Generated by Django 5.2.5 on 2026-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nested_inframe_deletions_per_cds_pc_variantcancertypepatientcount_nested_inframe_deletions_pe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='classification',
            field=models.CharField(blank=True, help_text='Variant_Classification', max_length=600, null=True),
        ),
    ]
