# Generated by Django 5.2.5 on 2026-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0004_rename_same_or_downstream_truncating_variants_per_cds_pc_variantcancertypepatientcount_same_or_downs",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="protein_pos",
            field=models.TextField(help_text="Protein_position", null=True),
        ),
    ]
