# Generated by Django 4.2.23 on 2026-04-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_make_classification_nullable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variantcancertypepatientcount",
            old_name="same_or_downstream_truncating_variants_per_cds_pc",
            new_name="same_or_downstream_truncating_variants_per_aa_pc",
        ),
        migrations.RemoveField(model_name="variant", name="classification",),
    ]
